import { Box, Button, Typography } from '@mui/material';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Nav from '@/src/components/Nav';
import Image from 'next/image';

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>POS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav>
          {/* <Typography variant="h6" fontWeight={700} className={styles.title}>
            AKHIRO POS
          </Typography> */}
        </Nav>

        <Box
          sx={{
            borderRadius: 5,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            marginTop: '-80px',
            padding: '0 20px', // Optional: Add some horizontal padding
          }}
        >
          <Box>
            <Box sx={{ width: '100%', textAlign: 'center' }} onClick={() => router.push('/pos')}>
              <Image src="/logoscan2.png" width={300} height={200} alt="Picture of the author" />
            </Box>

            <Box
              sx={{
                width: '100%',
              }}
            >
              <Button
                variant="contained"
                onClick={() => router.push('/utang')}
                sx={{
                  textAlign: 'center',
                  width: '100%',
                  mb: '5px',
                }}
              >
                LISTAHAN
              </Button>
              <Button
                variant="contained"
                onClick={() => router.push('/add')}
                sx={{
                  textAlign: 'center',
                  width: '100%',
                  mb: '5px',
                }}
              >
                ADD ITEM
              </Button>
              <Button
                variant="contained"
                onClick={() => router.push('/dashboard')}
                sx={{
                  textAlign: 'center',
                  width: '100%',
                  mb: '5px',
                }}
              >
                DASHBOARD
              </Button>
              <Button
                variant="contained"
                onClick={() => router.push('/admin')}
                sx={{
                  textAlign: 'center',
                  width: '100%',
                }}
              >
                ITEMS
              </Button>
            </Box>
          </Box>
          <Box p={2} pt={5}>
            <Typography textAlign="center" fontSize="10px">
              Streamline your sales process with our Mobile POS system! Easily manage transactions,
              track sales, and handle inventory on the go.
            </Typography>
          </Box>
        </Box>
      </main>
    </>
  );
}
