import { Box } from '@mui/material';
import Head from 'next/head';
import Nav from '@/src/components/Nav';
import ScanItems from '@/src/components/Mobile/ScanItems';
import { GetServerSideProps } from 'next';
import { parse } from 'cookie';

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { req } = context;
  const cookie = req.headers.cookie;

  const cookies = cookie ? parse(cookie) : undefined;
  const isAuthenticated = cookies?.t ? true : false;

  if (!isAuthenticated) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  return {
    props: {
      fullMode: false,
    },
  };
};

export default function Home() {
  return (
    <>
      <Head>
        <title>POS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <Box sx={{}}>
          <>
            <Box>
              <ScanItems />
            </Box>
          </>
        </Box>
      </main>
    </>
  );
}
