import { Box, Button, Typography } from '@mui/material';
import styles from './styles.module.css';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>POS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: '10px' }}>
        <Typography variant="h6" fontWeight={700} className={styles.title}>
          AKHIRO POS
        </Typography>

        <Box
          sx={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            height: '80vh', // Full viewport height
            padding: '0 20px', // Optional: Add some horizontal padding
            gap: '10px', // Space between the buttons
          }}
        >
          <Button
            variant="contained"
            onClick={() => router.push('/pos')}
            sx={{
              padding: '50px 30px',
              border: '1px solid gray',
              borderRadius: '20px',
              textAlign: 'center',
              width: '100%',
              maxWidth: '400px', // Optional: Set a maximum width for the button
            }}
          >
            POS
          </Button>
          <Box
            sx={{
              display: 'flex',
              gap: '10px',
              width: '100%',
              maxWidth: '400px', // Optional: Set a maximum width for the container
            }}
          >
            <Button
              variant="contained"
              onClick={() => router.push('/utang')}
              sx={{
                border: '1px solid gray',
                borderRadius: '20px',
                padding: '50px 30px',
                textAlign: 'center',
                width: '45%',
              }}
            >
              LISTAHAN
            </Button>
            <Button
              variant="contained"
              onClick={() => router.push('/add')}
              sx={{
                border: '1px solid gray',
                borderRadius: '20px',
                padding: '50px 30px',
                textAlign: 'center',
                width: '45%',
              }}
            >
              ADD ITEM
            </Button>
          </Box>
        </Box>

        {/* <Box mt={2}>
          <ScanItems />
        </Box>
        <div className={styles.footer}>
          <Checkout />
        </div> */}
      </main>
    </>
  );
}
