import Checkout from '@/src/components/Mobile/CheckOut';
import ScanItems from '@/src/components/Mobile/ScanItems';
import { Box } from '@mui/material';
import styles from '../styles.module.css';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>POS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <ScanItems />
        </Box>
        <div className={styles.footer}>
          <Checkout />
        </div>
      </main>
    </>
  );
}
